default:
	#/Users/cmo/repos/moontrade/tinygo/build/tinygo build -o tinygo_art -scheduler coroutines -gc provided --print-allocs=. .
	/Users/cmo/repos/moontrade/tinygo/build/tinygo build -dumpssa -scheduler coroutines -gc provided -o tinygo_art .
	./tinygo_art
	#/Users/cmo/repos/moontrade/tinygo/build/tinygo test -o tinygo_art -scheduler coroutines -gc provided .
